apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: argocd-demo
        image: gitployio/argocd-demo
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
